---
abstract: 'Test Using Multiple Servers/Clients'
author:
  - 'The important bits by Tokuhiro Matsuno (Test::TCP)'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.93'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-TCP-Multi
no_index:
  directory:
    - inc
    - t
requires:
  Storable: 0
  Test::SharedFork: 0.11
  Time::HiRes: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/lestrrat/Test-TCP-Multi.git
version: 0.00004
